# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  # user_frameworks!
  
  # Pods for Runner
  project'/Users/abdulbasit/AndroidStudioProjects/utility_app/ios/Runner.xcodeproj'
end
